export const UPDATE_ORIGINAL_ID = 'UPDATE_ORIGINAL_ID'
export const UPDATE_ORIGINAL_AMOUNT = 'UPDATE_ORIGINAL_AMOUNT'
export const CONVERT_ORIGINAL = 'CONVERT_ORIGINAL'

export const UPDATE_OUTCOME_ID = 'UPDATE_OUTCOME_ID'
export const UPDATE_OUTCOME_AMOUNT = 'UPDATE_OUTCOME_AMOUNT'
export const CONVERT_OUTCOME = 'CONVERT_OUTCOME'

export const LOAD_LIST = 'LOAD_LIST'

export const UPDATE_RATE = 'UPDATE_RATE'
